## Server Configuration
#server:
#  port: 25672
#
## Spring Application Configuration
#spring:
#  application:
#    name: rabbitmq-consumer
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: 1234
#
## RabbitMQ Configuration
#rabbitmq:
#  exchange:
#    name: party.notification.exchange # 메시지를 전달하는 Topic Exchange 이름
#  routing-keys:
#    - seoul.gangnam.* # 강남 지역 라우팅 키
#    - seoul.jongro.*  # 종로 지역 라우팅 키
#    - seoul.songpa.*  # 송파 지역 라우팅 키
#
#  queues:
#    - name: gangnam.notification.queue # 강남 지역 큐
#      routing-key: seoul.gangnam.* # 강남 지역 라우팅 키에 매핑
#    - name: jongro.notification.queue  # 종로 지역 큐
#      routing-key: seoul.jongro.*  # 종로 지역 라우팅 키에 매핑
#    - name: songpa.notification.queue  # 송파 지역 큐
#      routing-key: seoul.songpa.*  # 송파 지역 라우팅 키에 매핑
#
#  dead-letter:
#    queue:
#      name: party.notification.dlq # 모든 메시지의 Dead Letter Queue
#    exchange:
#      name: party.notification.dlx # Dead Letter Exchange
#    routing-key: dlq.# # Dead Letter 라우팅 키
