server:
  port: 8383

## Spring Application Configuration
rabbitmq:
  exchange:
    name: party.exchange
    dead-letter: exchange.dlx
  queues:
    party.create: party.create.queue
    party.cancel: party.cancel.queue
    chat.create: party.chat.create.queue
    dead-letter: queue.dlx
  routing-keys:
    party.create: party.create
    party.cancel: party.cancel
    chat.create: party.chat.create
  ttl: 60000 # 메시지 TTL (밀리초)