server:
  port: 8383

## Spring Application Configuration
rabbitmq:
  exchange:
    name: notifications.topic # Topic Exchange 이름
    dead-letter: notifications.dlx # Dead Letter Exchange 이름
  queue:
    name: notification_queue # Queue 이름 접두어
    dead-letter: notification_queue.dlx # Dead Letter Queue 이름
  ttl: 60000 # 메시지 TTL (밀리초)