name: 509test CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    name: Build Docker image and push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
        
      - name: Write Profile
        run: |
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./src/main/resources/application-prod.yml
          cat ./src/main/resources/application.yml

      - name: Copy Profiles to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./src/main/resources/application*.yml
          target: /home/ubuntu/project509/

      - name: Build with Gradle
        run: ./gradlew build -x test
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          REGION="ap-northeast-2"
          ECR_REPOSITORY="rednotice-ecr"
          
          docker build -f Dockerfile -t 509test:latest .
          docker tag 509test:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/509test:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/509test:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Debug Environment Variables
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" > debug_env.txt
          echo "DB_URL=${{ secrets.DB_URL }}" >> debug_env.txt
          echo "CLIENT_BASIC_URL=${{ secrets.CLIENT_BASIC_URL }}" >> debug_env.txt
      - name: Copy Debug File to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: debug_env.txt
          target: /home/ubuntu/
    
      - name: Docker image pull & Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            REGION="ap-northeast-2"
            ECR_REPOSITORY="509test"
            IMAGE_TAG="latest"          
            AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}

            docker stop app || true
            docker rm app || true
            
            aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/509test:latest
            
            docker run -d --name app -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_URL=${{ secrets.DB_URL }} \
            -e KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY }} \
            -e KAKAO_URL=${{ secrets.KAKAO_URL }} \
            -e CLIENT_BASIC_URL=${{ secrets.CLIENT_BASIC_URL }} \
            $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
